### ISSUE TITLE
使用物理杜甫，但是使用一键创建kvm的时候出现下面错误。

### ISSUE THREAD

**Issue by cnken** [oneclickvirt/pve#19]
主机能Ping通外网。

Host available IP interval query failed
宿主机可用IP区间查询失败

**Comment by cnken** [comment]
![Uploading 1.png…]()

**Comment by cnken** [comment]
![1](https://github.com/oneclickvirt/pve/assets/11863563/0667b794-c287-48a5-a746-4e149627fa3e)

**Comment by cnken** [comment]
![1](https://github.com/oneclickvirt/pve/assets/11863563/7ae9c256-2cd2-492a-858c-150b55e96686)
![2](https://github.com/oneclickvirt/pve/assets/11863563/73e5a352-a319-488f-a9a3-a5c4786f67fd)
![3](https://github.com/oneclickvirt/pve/assets/11863563/490719ab-d36e-4f43-baf9-e2369c7d63a0)
![4](https://github.com/oneclickvirt/pve/assets/11863563/161d005c-4534-45b6-8f62-b1e204303401)

**Comment by cnken** [comment]
实在抱歉，下午因为着急，让客服重装，自己也没去注意这方面，刚才试了一下，用别的IP登录无法登录，应该是未绑定剩下的四个可用IP。

**Comment by cnken** [comment]
是的，5IP的杜甫

**Comment by spiritLHLS** [comment]
比如主IPV4地址是1.1.1.1
未绑定的是 1.1.1.2 1.1.1.3
这样的

**Comment by cnken** [comment]
> 比如主IPV4地址是1.1.1.1 未绑定的是 1.1.1.2 1.1.1.3 这样的

是的。

**Comment by spiritLHLS** [comment]
那应该就是脚本问题了，没有识别到子网区间

**Comment by cnken** [comment]
*.*.*.26/30

*.*.*.26
*.*.*.27
*.*.*.28
*.*.*.29
*.*.*.30
这样子的

**Comment by spiritLHLS** [comment]
> ```
> lshw -C network | awk '/logical name:/{print $3}' | head -1
> ```
> 
> 和
> 
> ```
> interface=$(lshw -C network | awk '/logical name:/{print $3}' | head -1)
> grep -A 1 "iface ${interface}" /etc/network/interfaces | grep "address"
> ```
> 
> 执行一下看看

估计其中一个输出为空或者有误

**Comment by spiritLHLS** [comment]
额...我在本号仅使用 邮件/issues/TG 联系陌生人

**Comment by spiritLHLS** [comment]
> > 额...我在本号仅使用 邮件/issues/TG 联系陌生人
> 
> 理解，我们tg谈可以吗？

https://t.me/spiritlhl_bot
