### ISSUE TITLE
服务商ipv4 和ipv6出口在不同网卡时候出现问题

### ISSUE THREAD

**Issue by miaojior** [oneclickvirt/pve#20]
我的服务商在eth0（00:12.0 Ethernet controller: Red Hat, Inc. Virtio network device）提供ipv4
在eth1（00:13.0 Ethernet controller: Red Hat, Inc. Virtio network device）提供ipv6
使用脚本安装pve重启之后ipv6失联  ifconfig之后发现没有eth1

**Comment by spiritLHLS** [comment]
是否能提供厂商名字？我测试了这么多大厂和VPS商家，目前暂时没有遇到你这种情况

**Comment by miaojior** [comment]
鸡仔云 重庆移动的nat  bigchick.xyz 
测试机器的ip和密码邮箱发给您了

**Comment by miaojior** [comment]
> 是否能提供厂商名字？我测试了这么多大厂和VPS商家，目前暂时没有遇到你这种情况

鸡仔云 重庆移动的nat bigchick.xyz
测试机器的ip和密码邮箱发给您了

**Comment by spiritLHLS** [comment]
> > 是否能提供厂商名字？我测试了这么多大厂和VPS商家，目前暂时没有遇到你这种情况
> 
> 鸡仔云 重庆移动的nat bigchick.xyz 测试机器的ip和密码邮箱发给您了

看到了，我看看啥情况

**Comment by spiritLHLS** [comment]
商家本身用的本项目下的镜像开的虚拟机？

**Comment by miaojior** [comment]
> 商家本身用的本项目下的镜像开的虚拟机？

这个我不清楚

**Comment by miaojior** [comment]
> 商家本身用的本项目下的镜像开的虚拟机？

这样会有什么限制么

**Comment by spiritLHLS** [comment]
> > 商家本身用的本项目下的镜像开的虚拟机？
> 
> 这样会有什么限制么

没有

还有另一个问题，是不是商家面板有防火墙设置，8006没开放

**Comment by spiritLHLS** [comment]
内部防火墙我关了，但8006不通，打不开网页面板

**Comment by miaojior** [comment]
> 内部防火墙我关了，但8006不通，打不开网页面板
ipv4 需要端口转发 10060

**Comment by spiritLHLS** [comment]
情况过于特殊

https://github.com/oneclickvirt/pve/issues/11

只能通过手动修改配置文件解决，附加的时候v6接eth1而不是eth0即可

商家本身使用的本项目的镜像，八成开设的时候也使用的本项目，你的需求约等于嵌套再嵌套开设

**Comment by spiritLHLS** [comment]
如果只是需要切分资源非必须KVM虚拟化，建议使用incus或lxd进行切分，使用一键虚拟化项目的其他方式进行虚拟化
